sudo: required

language: python
python:
  - 2.7

services:
  - docker

install:
  - docker run --rm -t -v "$TRAVIS_BUILD_DIR:/tmp/pandorafms" -p 80:80 pandorafms/pandorafms-base /tmp/pandorafms/tests/test.sh
  - pip install selenium PyVirtualDisplay
  
script:
  - python $TRAVIS_BUILD_DIR/tests/run_console_tests.py

